export const STRIPE_SECRET_KEY =
  process.env.RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_SECRET_KEY;
export const STRIPE_PAYMENT_METHODS =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_PAYMENT_METHODS;
export const STRIPE_CURRENCY =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_CURRENCY;
export const STRIPE_AMOUNT_MULTIPLIER =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_AMOUNT_MULTIPLIER;
export const STRIPE_PRODUCT_ID =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_PRODUCT_ID;
export const STRIPE_PRODUCT_NAME =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_PRODUCT_NAME;
export const STRIPE_PRODUCT_DESCRIPTION =
  process.env.GATSBY_RAAE_GATSBY_PLUGIN_DONATIONS_STRIPE_PRODUCT_DESCRIPTION;
